### ISSUE TITLE
How to extract "thin" image 

### ISSUE THREAD

**Issue by llcuong** [gioelecrispo/wor#3]
Hello sir, I am very impressed with this project. I have read about the code to output the skel of the image. but I have questions about how to output the file "image_thin.png" from the input image. How to edit skeleton to thin. i want to work with only 1 input image. Thank you sir.

**Comment by gioelecrispo** [comment]
Hello @llcuong, thank you for your interest. 
As you probably know at this point, these images are obtained through the Bresenham's algorithm, which is a general and well-known interpolation algorithm and therefore is not provided in my Github code. If interested, you can find many implementation of the Bresenham's algorithm on the web. 
Closing the issue.
